# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2

jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.10.3
      - image: rethinkdb:2.3.6
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/rethinkDB:2.3.6

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force  # install Hex locally (without prompt)
      - run: mix local.rebar --force  # fetch a copy of rebar (without prompt)
      # specify any bash command here prefixed with `run: `
      - run: mix deps.get
      - run: mix do deps.get, compile
      #- run: mix ecto.create
      
      - run: mix do run
      
  deploy:
     docker: # Use the Docker executor for the deploy job
       - image: circleci/elixir:1.10.3
       - image: rethinkdb:2.3.6
   steps:
       - checkout
       - aws-s3/sync:
           from: bucket
           to: 's3://elixirmyblogbucket'
           arguments: | # Optional arguments
             --acl public-read \
             --cache-control "max-age=86400"
           overwrite: true # default is false
           
 workflows: # Define a Workflow running the build job, then the deploy job
   version: 2
   build-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build
           filters:
             branches:
               only: master
