# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2.1

orbs:
#  aws-s3: circleci/aws-s3@1.0.15 # use the AWS S3 orb in your config
  aws-ecs: circleci/aws-ecs@1.1.0

workflows: # Define a Workflow running the build job, then the deploy job
  version: 2
  build-deploy:
    jobs:
#      - build
      - deploy:
#          requires:
#            - build
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.10.3
#      - image: rethinkdb:2.3.6
      - image: circleci/postgres:9.6.2-alpine
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/rethinkDB:2.3.6

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force  # install Hex locally (without prompt)
      - run: mix local.rebar --force  # fetch a copy of rebar (without prompt)
      # specify any bash command here prefixed with `run: `
      - run: mix deps.get
      - run: mix do deps.get, compile
      #- run: mix ecto.create
      - run: mix do run

  deploy:
    docker:
      - image: circleci/python:3.6.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: pip install numpy
      - run: yes | sudo pip install gigalixir
      - run: gigalixir login --email "ana20bianca@gmail.com" --password "0269588218"
      - run: git push gigalixir master

#  deploy:
#    docker: # Use the Docker executor for the deploy job
#      - image: circleci/elixir:1.10.3
#      - image: circleci/postgres:9.6.2-alpine
#    steps:
#      - checkout
#      - run: pwd
#      - run: ls
#      - aws-s3/sync:
#          from: '/home/circleci/project'
#          to: 's3://elixirmyblogbucket/'
#          arguments: | # Optional arguments
#            --acl public-read \
#            --cache-control "max-age=86400"
#          overwrite: true # default is false
